// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// eq_prior_indiv
double eq_prior_indiv(int age, double sigma, double het, std::vector<double> vx, std::vector<double> mi, double ii_shape, double ii_rate);
RcppExport SEXP _iccm_eq_prior_indiv(SEXP ageSEXP, SEXP sigmaSEXP, SEXP hetSEXP, SEXP vxSEXP, SEXP miSEXP, SEXP ii_shapeSEXP, SEXP ii_rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type het(hetSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type vx(vxSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type mi(miSEXP);
    Rcpp::traits::input_parameter< double >::type ii_shape(ii_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type ii_rate(ii_rateSEXP);
    rcpp_result_gen = Rcpp::wrap(eq_prior_indiv(age, sigma, het, vx, mi, ii_shape, ii_rate));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_iccm_eq_prior_indiv", (DL_FUNC) &_iccm_eq_prior_indiv, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_iccm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
