# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Childs equilibrium number of previous infections
#'
#' @param age Age
#' @param sigma FOI
#' @param het Heterogeneity
#' @param vx vaccine impact wrt age (pre compute across whole age range)
#' @param mi Maternal immunity impact (pre computre across whole age range)
#' @param ii_shape Infection immunity shape parameter
#' @param ii_rate Infection immunity rate parameter
eq_prior_indiv <- function(age, sigma, het, vx, mi, ii_shape, ii_rate) {
    .Call(`_iccm_eq_prior_indiv`, age, sigma, het, vx, mi, ii_shape, ii_rate)
}

